structure(list(Representative = structure(c(103L, 119L, 34L, 
46L, 100L, 87L, 156L, 140L, 147L, 90L), .Label = c("Adam Kinzinger", 
"Alan Lowenthal", "Andrew Garbarino", "Anthony Gonzalez", "Ashley Hinson", 
"August Pfluger", "Austin Scott", "Barbara Comstock", "Bill Cassidy", 
"Bill Flores", "Bill Hagerty", "Bill Keating", "Bill Pascrell", 
"Blake Moore", "Bob Gibbs", "Brad Schneider", "Brian Higgins", 
"Brian Mast", "Bryan Steil", "Carlos Curbelo", "Carol Miller", 
"Cheri Bustos", "Chris Jacobs", "Chris Van Hollen", "Christopher Coons", 
"Cynthia Axne", "Cynthia Lummis", "Dan Crenshaw", "Dan Sullivan", 
"Daniel Meuser", "Dave Joyce", "Dave Trott", "David McKinley", 
"David Perdue", "David Price", "David Rouzer", "David Trone", 
"Dean Phillips", "Debbie Dingell", "Debbie Wasserman Schultz", 
"Deborah Ross", "Derek Kilmer", "Dianne Feinstein", "Donald Beyer", 
"Donald McEachin", "Donna Shalala", "Dwight Evans", "Earl Blumenauer", 
"Ed Case", "Ed Perlmutter", "Elaine Luria", "Frank LoBiondo", 
"Frank Pallone", "French Hill", "Garret Graves", "Gary Palmer", 
"Gary Peters", "Gerald Connolly", "Gilbert Cisneros", "Greg Gianforte", 
"Greg Murphy", "Harley Rouda", "Jack Reed", "Jackie Speier", 
"Jacky Rosen", "James Comer", "James Inhofe", "Jerry Moran", 
"Jim Banks", "Jim Langevin", "Joe Courtney", "Joe Manchin", "Joe Morelle", 
"John Cornyn", "John Curtis", "John Garamendi", "John Hickenlooper", 
"John Hoeven", "John Larson", "John Rose", "John Rutherford", 
"John Yarmuth", "Josh Gottheimer", "Judy Chu", "Justin Amash", 
"K. Conaway", "Katherine Clark", "Kathy Castor", "Kathy Manning", 
"Kelly Loeffler", "Ken Buck", "Kevin Hern", "Kevin Yoder", "Kim Schrier", 
"Lamar Smith", "Larry Bucshon", "Lizzie Fletcher", "Lloyd Doggett", 
"Lloyd Smucker", "Lois Frankel", "Lori Trahan", "Madison Cawthorn", 
"Marie Newman", "Mario Diaz-Balart", "Marjorie Greene", "Mark Green", 
"Mark Meadows", "Mark Warner", "Michael Burgess", "Michael Enzi", 
"Michael Guest", "Mike Gallagher", "Mike Garcia", "Mike Simpson", 
"Mikie Sherrill", "Mitch McConnell", "Mo Brooks", "Nancy Pelosi", 
"Pat Fallon", "Pat Roberts", "Patrick Toomey", "Patty Murray", 
"Pete Sessions", "Peter Meijer", "Peter Visclosky", "Peter Welch", 
"Richard Blumenthal", "Richard Burr", "Rick Allen", "Robert Latta", 
"Robert Scott", "Robert Wittman", "Rod Blum", "Roger Marshall", 
"Ron Wyden", "Roy Blunt", "Sara Jacobs", "Scott Peters", "Sean Maloney", 
"Sheldon Whitehouse", "Shelley Capito", "Stephanie Murphy", "Steve Cohen", 
"Susan Brooks", "Susan Collins", "Susan Davis", "Susie Lee", 
"Suzan DelBene", "Tammy Duckworth", "Ted Cruz", "Thomas Carper", 
"Thomas Suozzi", "Tim Kaine", "Tina Smith", "Tom MacArthur", 
"Tom Malinowski", "Tom O'Halleran", "Tom Rice", "Tom Rooney", 
"Tom Udall", "Tommy Tuberville", "Van Taylor", "Victoria Spartz", 
"Virginia Foxx", "Warren Davidson", "William Timmons", "Zoe Lofgren"
), class = "factor"), n = c(41L, 36L, 289L, 75L, 56L, 45L, 37L, 
45L, 103L, 61L), sale_count = c(55L, 64L, 523L, 136L, 104L, 84L, 
73L, 89L, 204L, 121L), percent = c(0.745454545454545, 0.5625, 
0.552581261950287, 0.551470588235294, 0.538461538461538, 0.535714285714286, 
0.506849315068493, 0.50561797752809, 0.504901960784314, 0.504132231404959
)), class = c("rowwise_df", "tbl_df", "tbl", "data.frame"), row.names = c(NA, 
-10L), groups = structure(list(.rows = structure(list(1L, 2L, 
    3L, 4L, 5L, 6L, 7L, 8L, 9L, 10L), ptype = integer(0), class = c("vctrs_list_of", 
"vctrs_vctr", "list"))), row.names = c(NA, -10L), class = c("tbl_df", 
"tbl", "data.frame")))
